/**
 * bronzeWrite — append-only write to hx_events_bronze
 * Source: HARVYX_BACKEND_RULES.md § 6 (Bronze write rule)
 * Rule: INSERT only. Never UPDATE or DELETE. No logic beyond the insert.
 */

import { Pool } from 'pg';
import type { HxBronzeEvent } from '../types/hx.types';
import { hxLogger } from './hx-logger';

const pool = new Pool({
  connectionString: process.env.HX_DATABASE_URL,
  max: 5,
  idleTimeoutMillis: 30_000,
  connectionTimeoutMillis: 5_000,
});

/**
 * Append one event to hx_events_bronze.
 * id and created_at are generated by the database.
 * This function has no side effects beyond the single INSERT.
 */
export async function bronzeWrite(event: HxBronzeEvent): Promise<void> {
  await pool.query(
    `INSERT INTO hx_events_bronze
       (event_type, source_module, entity_id, entity_type, payload)
     VALUES ($1, $2, $3, $4, $5)`,
    [
      event.event_type,
      event.source_module,
      event.entity_id ?? null,
      event.entity_type ?? null,
      JSON.stringify(event.payload),
    ],
  );

  hxLogger.debug('hx-bronze', 'event written', {
    event_type: event.event_type,
    source_module: event.source_module,
    entity_id: event.entity_id,
  });
}
