#!/usr/bin/env python3
"""Create missing folders under public/assets/verticals/.

SAFETY:
  - Uses os.makedirs(path, exist_ok=True) ONLY.
  - Never deletes, renames, moves, or overwrites anything.
  - If a folder already exists, it is silently skipped.

FLAGS:
  --dry-run                  print the plan, create nothing
  --vertical 01-apparels     run for one vertical only
                             (valid: 01-apparels, 02-fmcg)

USAGE:
  python3 scripts/create_missing_folders.py --dry-run
  python3 scripts/create_missing_folders.py --vertical 01-apparels --dry-run
  python3 scripts/create_missing_folders.py
"""
import argparse
import os
import sys

# Project root = parent of this script's directory
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
BASE = os.path.join(PROJECT_ROOT, "public", "assets", "verticals")

PATHS = [
    # ---------------- 01-apparels ----------------
    # apparel/mens-wear
    "01-apparels/categories/apparel/mens-wear/shirts",
    "01-apparels/categories/apparel/mens-wear/trousers",
    "01-apparels/categories/apparel/mens-wear/suits",
    "01-apparels/categories/apparel/mens-wear/t-shirts",
    "01-apparels/categories/apparel/mens-wear/denim",
    "01-apparels/categories/apparel/mens-wear/knitwear",
    "01-apparels/categories/apparel/mens-wear/outerwear",
    "01-apparels/categories/apparel/mens-wear/ethnic",
    "01-apparels/categories/apparel/mens-wear/polo",
    "01-apparels/categories/apparel/mens-wear/hoodies",
    "01-apparels/categories/apparel/mens-wear/shorts",
    "01-apparels/categories/apparel/mens-wear/swimwear",
    "01-apparels/categories/apparel/mens-wear/underwear",
    "01-apparels/categories/apparel/mens-wear/socks",
    # apparel/womens-wear
    "01-apparels/categories/apparel/womens-wear/tops",
    "01-apparels/categories/apparel/womens-wear/dresses",
    "01-apparels/categories/apparel/womens-wear/abayas",
    "01-apparels/categories/apparel/womens-wear/trousers",
    "01-apparels/categories/apparel/womens-wear/knitwear",
    "01-apparels/categories/apparel/womens-wear/ethnic",
    "01-apparels/categories/apparel/womens-wear/outerwear",
    "01-apparels/categories/apparel/womens-wear/skirts",
    "01-apparels/categories/apparel/womens-wear/blouses",
    "01-apparels/categories/apparel/womens-wear/swimwear",
    "01-apparels/categories/apparel/womens-wear/jumpsuits",
    "01-apparels/categories/apparel/womens-wear/cardigans",
    "01-apparels/categories/apparel/womens-wear/coats",
    # apparel/teens
    "01-apparels/categories/apparel/teens/boys-teens/t-shirts",
    "01-apparels/categories/apparel/teens/boys-teens/jeans",
    "01-apparels/categories/apparel/teens/boys-teens/hoodies",
    "01-apparels/categories/apparel/teens/boys-teens/shorts",
    "01-apparels/categories/apparel/teens/boys-teens/shirts",
    "01-apparels/categories/apparel/teens/boys-teens/tracksuits",
    "01-apparels/categories/apparel/teens/boys-teens/swimwear",
    "01-apparels/categories/apparel/teens/boys-teens/underwear",
    "01-apparels/categories/apparel/teens/girls-teens/tops",
    "01-apparels/categories/apparel/teens/girls-teens/jeans",
    "01-apparels/categories/apparel/teens/girls-teens/dresses",
    "01-apparels/categories/apparel/teens/girls-teens/hoodies",
    "01-apparels/categories/apparel/teens/girls-teens/skirts",
    "01-apparels/categories/apparel/teens/girls-teens/swimwear",
    "01-apparels/categories/apparel/teens/girls-teens/underwear",
    "01-apparels/categories/apparel/teens/girls-teens/activewear",
    # apparel/kids-wear
    "01-apparels/categories/apparel/kids-wear/boys/t-shirts",
    "01-apparels/categories/apparel/kids-wear/boys/shorts",
    "01-apparels/categories/apparel/kids-wear/boys/shirts",
    "01-apparels/categories/apparel/kids-wear/boys/trousers",
    "01-apparels/categories/apparel/kids-wear/boys/hoodies",
    "01-apparels/categories/apparel/kids-wear/boys/swimwear",
    "01-apparels/categories/apparel/kids-wear/boys/underwear",
    "01-apparels/categories/apparel/kids-wear/boys/jackets",
    "01-apparels/categories/apparel/kids-wear/girls/tops",
    "01-apparels/categories/apparel/kids-wear/girls/dresses",
    "01-apparels/categories/apparel/kids-wear/girls/skirts",
    "01-apparels/categories/apparel/kids-wear/girls/leggings",
    "01-apparels/categories/apparel/kids-wear/girls/swimwear",
    "01-apparels/categories/apparel/kids-wear/girls/underwear",
    "01-apparels/categories/apparel/kids-wear/girls/jackets",
    "01-apparels/categories/apparel/kids-wear/infants/rompers",
    "01-apparels/categories/apparel/kids-wear/infants/onesies",
    "01-apparels/categories/apparel/kids-wear/infants/sleepsuits",
    "01-apparels/categories/apparel/kids-wear/infants/bibs",
    "01-apparels/categories/apparel/kids-wear/infants/hats",
    "01-apparels/categories/apparel/kids-wear/infants/socks",
    "01-apparels/categories/apparel/kids-wear/infants/sets",
    "01-apparels/categories/apparel/kids-wear/toddlers/tops",
    "01-apparels/categories/apparel/kids-wear/toddlers/bottoms",
    "01-apparels/categories/apparel/kids-wear/toddlers/dresses",
    "01-apparels/categories/apparel/kids-wear/toddlers/sets",
    "01-apparels/categories/apparel/kids-wear/toddlers/outerwear",
    "01-apparels/categories/apparel/kids-wear/toddlers/swimwear",
    "01-apparels/categories/apparel/kids-wear/school-uniforms/boys-uniform",
    "01-apparels/categories/apparel/kids-wear/school-uniforms/girls-uniform",
    "01-apparels/categories/apparel/kids-wear/school-uniforms/pe-kit",
    "01-apparels/categories/apparel/kids-wear/school-uniforms/shoes",
    # apparel/baby
    "01-apparels/categories/apparel/baby/newborn/sleepsuits",
    "01-apparels/categories/apparel/baby/newborn/vests",
    "01-apparels/categories/apparel/baby/newborn/hats",
    "01-apparels/categories/apparel/baby/newborn/mittens",
    "01-apparels/categories/apparel/baby/newborn/socks",
    "01-apparels/categories/apparel/baby/newborn/sets",
    "01-apparels/categories/apparel/baby/newborn/swaddles",
    "01-apparels/categories/apparel/baby/infant/rompers",
    "01-apparels/categories/apparel/baby/infant/tops",
    "01-apparels/categories/apparel/baby/infant/bottoms",
    "01-apparels/categories/apparel/baby/infant/outerwear",
    "01-apparels/categories/apparel/baby/infant/sets",
    "01-apparels/categories/apparel/baby/toddler/tops",
    "01-apparels/categories/apparel/baby/toddler/bottoms",
    "01-apparels/categories/apparel/baby/toddler/dresses",
    "01-apparels/categories/apparel/baby/toddler/outerwear",
    "01-apparels/categories/apparel/baby/toddler/sets",
    # apparel/sportswear
    "01-apparels/categories/apparel/sportswear/activewear",
    "01-apparels/categories/apparel/sportswear/tracksuits",
    "01-apparels/categories/apparel/sportswear/swimwear",
    "01-apparels/categories/apparel/sportswear/performance-tees",
    "01-apparels/categories/apparel/sportswear/sports-bras",
    "01-apparels/categories/apparel/sportswear/compression",
    "01-apparels/categories/apparel/sportswear/yoga",
    "01-apparels/categories/apparel/sportswear/cycling",
    # lingerie
    "01-apparels/categories/lingerie/bras/balcony",
    "01-apparels/categories/lingerie/bras/padded",
    "01-apparels/categories/lingerie/bras/underwired",
    "01-apparels/categories/lingerie/bras/sports-bra",
    "01-apparels/categories/lingerie/bras/strapless",
    "01-apparels/categories/lingerie/bras/maternity",
    "01-apparels/categories/lingerie/bras/non-wired",
    "01-apparels/categories/lingerie/panties/briefs",
    "01-apparels/categories/lingerie/panties/thongs",
    "01-apparels/categories/lingerie/panties/brazilian",
    "01-apparels/categories/lingerie/panties/boyshorts",
    "01-apparels/categories/lingerie/panties/high-waist",
    "01-apparels/categories/lingerie/panties/period-underwear",
    "01-apparels/categories/lingerie/nightwear/pajamas",
    "01-apparels/categories/lingerie/nightwear/nightgowns",
    "01-apparels/categories/lingerie/nightwear/robes",
    "01-apparels/categories/lingerie/nightwear/slippers",
    "01-apparels/categories/lingerie/shapewear/bodysuits",
    "01-apparels/categories/lingerie/shapewear/waist-trainers",
    "01-apparels/categories/lingerie/shapewear/thigh-shapers",
    "01-apparels/categories/lingerie/hosiery/tights",
    "01-apparels/categories/lingerie/hosiery/stockings",
    "01-apparels/categories/lingerie/hosiery/socks",
    "01-apparels/categories/lingerie/hosiery/knee-highs",
    "01-apparels/categories/lingerie/loungewear/sets",
    "01-apparels/categories/lingerie/loungewear/tops",
    "01-apparels/categories/lingerie/loungewear/bottoms",
    # home-textiles
    "01-apparels/categories/home-textiles/bed-linen/sheets",
    "01-apparels/categories/home-textiles/bed-linen/duvets",
    "01-apparels/categories/home-textiles/bed-linen/pillowcases",
    "01-apparels/categories/home-textiles/bed-linen/comforters",
    "01-apparels/categories/home-textiles/bed-linen/bedspreads",
    "01-apparels/categories/home-textiles/bed-linen/quilts",
    "01-apparels/categories/home-textiles/bath-linen/towels",
    "01-apparels/categories/home-textiles/bath-linen/bathrobes",
    "01-apparels/categories/home-textiles/bath-linen/bath-mats",
    "01-apparels/categories/home-textiles/bath-linen/washcloths",
    "01-apparels/categories/home-textiles/bath-linen/hand-towels",
    "01-apparels/categories/home-textiles/curtains/blackout",
    "01-apparels/categories/home-textiles/curtains/sheer",
    "01-apparels/categories/home-textiles/curtains/panel",
    "01-apparels/categories/home-textiles/curtains/eyelet",
    "01-apparels/categories/home-textiles/curtains/drapes",
    "01-apparels/categories/home-textiles/curtains/roman-blinds",
    "01-apparels/categories/home-textiles/kitchen/aprons",
    "01-apparels/categories/home-textiles/kitchen/tea-towels",
    "01-apparels/categories/home-textiles/kitchen/oven-mitts",
    "01-apparels/categories/home-textiles/kitchen/table-cloths",
    "01-apparels/categories/home-textiles/kitchen/placemats",
    "01-apparels/categories/home-textiles/kitchen/napkins",
    "01-apparels/categories/home-textiles/table/table-runners",
    "01-apparels/categories/home-textiles/table/tablecloths",
    "01-apparels/categories/home-textiles/table/coasters",
    # fabrics
    "01-apparels/categories/fabrics/cotton/woven",
    "01-apparels/categories/fabrics/cotton/knit",
    "01-apparels/categories/fabrics/cotton/organic",
    "01-apparels/categories/fabrics/cotton/dyed",
    "01-apparels/categories/fabrics/cotton/printed",
    "01-apparels/categories/fabrics/cotton/jersey",
    "01-apparels/categories/fabrics/cotton/poplin",
    "01-apparels/categories/fabrics/cotton/twill",
    "01-apparels/categories/fabrics/polyester/woven",
    "01-apparels/categories/fabrics/polyester/knit",
    "01-apparels/categories/fabrics/polyester/fleece",
    "01-apparels/categories/fabrics/polyester/micro-fiber",
    "01-apparels/categories/fabrics/polyester/recycled",
    "01-apparels/categories/fabrics/polyester/satin",
    "01-apparels/categories/fabrics/polyester/chiffon",
    "01-apparels/categories/fabrics/blends/poly-cotton",
    "01-apparels/categories/fabrics/blends/cvc",
    "01-apparels/categories/fabrics/blends/tc",
    "01-apparels/categories/fabrics/blends/modal-blend",
    "01-apparels/categories/fabrics/blends/bamboo",
    "01-apparels/categories/fabrics/blends/viscose",
    "01-apparels/categories/fabrics/blends/lycra",
    "01-apparels/categories/fabrics/denim/raw",
    "01-apparels/categories/fabrics/denim/washed",
    "01-apparels/categories/fabrics/denim/stretch",
    "01-apparels/categories/fabrics/denim/selvedge",
    "01-apparels/categories/fabrics/denim/recycled",
    "01-apparels/categories/fabrics/denim/black-denim",
    "01-apparels/categories/fabrics/denim/colored",
    "01-apparels/categories/fabrics/linen/plain",
    "01-apparels/categories/fabrics/linen/printed",
    "01-apparels/categories/fabrics/linen/blended",
    "01-apparels/categories/fabrics/linen/organic",
    "01-apparels/categories/fabrics/silk/charmeuse",
    "01-apparels/categories/fabrics/silk/chiffon",
    "01-apparels/categories/fabrics/silk/dupioni",
    "01-apparels/categories/fabrics/silk/organza",
    "01-apparels/categories/fabrics/silk/satin",
    "01-apparels/categories/fabrics/wool/merino",
    "01-apparels/categories/fabrics/wool/cashmere",
    "01-apparels/categories/fabrics/wool/lambswool",
    "01-apparels/categories/fabrics/wool/tweed",
    "01-apparels/categories/fabrics/wool/felt",
    "01-apparels/categories/fabrics/synthetic/nylon",
    "01-apparels/categories/fabrics/synthetic/acrylic",
    "01-apparels/categories/fabrics/synthetic/spandex",
    "01-apparels/categories/fabrics/synthetic/elastane",
    "01-apparels/categories/fabrics/synthetic/microfiber",
    # footwear (top-level)
    "01-apparels/categories/footwear/mens/sneakers",
    "01-apparels/categories/footwear/mens/dress-shoes",
    "01-apparels/categories/footwear/mens/boots",
    "01-apparels/categories/footwear/mens/loafers",
    "01-apparels/categories/footwear/mens/sandals",
    "01-apparels/categories/footwear/mens/slippers",
    "01-apparels/categories/footwear/mens/casual",
    "01-apparels/categories/footwear/mens/work-safety",
    "01-apparels/categories/footwear/mens/sports",
    "01-apparels/categories/footwear/womens/sneakers",
    "01-apparels/categories/footwear/womens/heels",
    "01-apparels/categories/footwear/womens/boots",
    "01-apparels/categories/footwear/womens/flats",
    "01-apparels/categories/footwear/womens/sandals",
    "01-apparels/categories/footwear/womens/slippers",
    "01-apparels/categories/footwear/womens/pumps",
    "01-apparels/categories/footwear/womens/wedges",
    "01-apparels/categories/footwear/kids/sneakers",
    "01-apparels/categories/footwear/kids/school-shoes",
    "01-apparels/categories/footwear/kids/boots",
    "01-apparels/categories/footwear/kids/sandals",
    "01-apparels/categories/footwear/kids/sports",
    "01-apparels/categories/footwear/teens/sneakers",
    "01-apparels/categories/footwear/teens/boots",
    "01-apparels/categories/footwear/teens/sandals",
    "01-apparels/categories/footwear/teens/sports",
    "01-apparels/categories/footwear/baby/pre-walkers",
    "01-apparels/categories/footwear/baby/first-walkers",
    "01-apparels/categories/footwear/baby/sandals",
    "01-apparels/categories/footwear/sports/running",
    "01-apparels/categories/footwear/sports/football",
    "01-apparels/categories/footwear/sports/basketball",
    "01-apparels/categories/footwear/sports/cricket",
    "01-apparels/categories/footwear/sports/tennis",
    "01-apparels/categories/footwear/sports/hiking",
    # accessories
    "01-apparels/categories/accessories/bags/totes",
    "01-apparels/categories/accessories/bags/handbags",
    "01-apparels/categories/accessories/bags/backpacks",
    "01-apparels/categories/accessories/bags/duffels",
    "01-apparels/categories/accessories/bags/clutches",
    "01-apparels/categories/accessories/bags/crossbody",
    "01-apparels/categories/accessories/bags/travel-bags",
    "01-apparels/categories/accessories/bags/wallets",
    "01-apparels/categories/accessories/belts/leather",
    "01-apparels/categories/accessories/belts/fabric",
    "01-apparels/categories/accessories/belts/woven",
    "01-apparels/categories/accessories/belts/casual",
    "01-apparels/categories/accessories/belts/formal",
    "01-apparels/categories/accessories/scarves/silk",
    "01-apparels/categories/accessories/scarves/wool",
    "01-apparels/categories/accessories/scarves/cotton",
    "01-apparels/categories/accessories/scarves/pashmina",
    "01-apparels/categories/accessories/scarves/printed",
    "01-apparels/categories/accessories/scarves/hijabs",
    "01-apparels/categories/accessories/hats/caps",
    "01-apparels/categories/accessories/hats/beanies",
    "01-apparels/categories/accessories/hats/fedoras",
    "01-apparels/categories/accessories/hats/sun-hats",
    "01-apparels/categories/accessories/jewellery/necklaces",
    "01-apparels/categories/accessories/jewellery/earrings",
    "01-apparels/categories/accessories/jewellery/bracelets",
    "01-apparels/categories/accessories/jewellery/rings",
    "01-apparels/categories/accessories/jewellery/anklets",
    "01-apparels/categories/accessories/sunglasses/aviator",
    "01-apparels/categories/accessories/sunglasses/wayfarer",
    "01-apparels/categories/accessories/sunglasses/sport",
    "01-apparels/categories/accessories/sunglasses/fashion",
    "01-apparels/categories/accessories/gloves/leather",
    "01-apparels/categories/accessories/gloves/wool",
    "01-apparels/categories/accessories/gloves/sports",
    "01-apparels/categories/accessories/gloves/winter",
    "01-apparels/categories/accessories/wallets/mens",
    "01-apparels/categories/accessories/wallets/womens",
    "01-apparels/categories/accessories/wallets/card-holders",

    # ---------------- 02-fmcg ----------------
    # food/dairy
    "02-fmcg/categories/food/dairy/cheese",
    "02-fmcg/categories/food/dairy/milk",
    "02-fmcg/categories/food/dairy/yogurt",
    "02-fmcg/categories/food/dairy/eggs",
    "02-fmcg/categories/food/dairy/butter",
    "02-fmcg/categories/food/dairy/cream",
    "02-fmcg/categories/food/dairy/condensed-milk",
    "02-fmcg/categories/food/dairy/powdered-milk",
    # food/meat-seafood
    "02-fmcg/categories/food/meat-seafood/beef",
    "02-fmcg/categories/food/meat-seafood/chicken",
    "02-fmcg/categories/food/meat-seafood/lamb",
    "02-fmcg/categories/food/meat-seafood/pork",
    "02-fmcg/categories/food/meat-seafood/fish",
    "02-fmcg/categories/food/meat-seafood/shrimp",
    "02-fmcg/categories/food/meat-seafood/deli-meats",
    "02-fmcg/categories/food/meat-seafood/sausages",
    "02-fmcg/categories/food/meat-seafood/halal-meat",
    # food/produce
    "02-fmcg/categories/food/produce/fresh-fruits",
    "02-fmcg/categories/food/produce/fresh-vegetables",
    "02-fmcg/categories/food/produce/herbs",
    "02-fmcg/categories/food/produce/salad",
    "02-fmcg/categories/food/produce/organic-produce",
    # food/breakfast-cereal
    "02-fmcg/categories/food/breakfast-cereal/cereals",
    "02-fmcg/categories/food/breakfast-cereal/oatmeal",
    "02-fmcg/categories/food/breakfast-cereal/granola",
    "02-fmcg/categories/food/breakfast-cereal/muesli",
    "02-fmcg/categories/food/breakfast-cereal/porridge",
    "02-fmcg/categories/food/breakfast-cereal/breakfast-bars",
    # food/bread-bakery
    "02-fmcg/categories/food/bread-bakery/sliced-bread",
    "02-fmcg/categories/food/bread-bakery/rolls-buns",
    "02-fmcg/categories/food/bread-bakery/tortillas",
    "02-fmcg/categories/food/bread-bakery/pita",
    "02-fmcg/categories/food/bread-bakery/flatbread",
    "02-fmcg/categories/food/bread-bakery/croissants",
    "02-fmcg/categories/food/bread-bakery/donuts",
    "02-fmcg/categories/food/bread-bakery/pies",
    # food/pantry/canned-goods
    "02-fmcg/categories/food/pantry/canned-goods/canned-vegetables",
    "02-fmcg/categories/food/pantry/canned-goods/canned-fruits",
    "02-fmcg/categories/food/pantry/canned-goods/canned-fish",
    "02-fmcg/categories/food/pantry/canned-goods/canned-meat",
    "02-fmcg/categories/food/pantry/canned-goods/canned-beans",
    "02-fmcg/categories/food/pantry/canned-goods/soups",
    "02-fmcg/categories/food/pantry/canned-goods/tomatoes",
    # food/pantry/condiments
    "02-fmcg/categories/food/pantry/condiments/ketchup",
    "02-fmcg/categories/food/pantry/condiments/mustard",
    "02-fmcg/categories/food/pantry/condiments/mayonnaise",
    "02-fmcg/categories/food/pantry/condiments/hot-sauce",
    "02-fmcg/categories/food/pantry/condiments/soy-sauce",
    "02-fmcg/categories/food/pantry/condiments/vinegar",
    "02-fmcg/categories/food/pantry/condiments/salad-dressing",
    # food/pantry/pasta-rice
    "02-fmcg/categories/food/pantry/pasta-rice/pasta",
    "02-fmcg/categories/food/pantry/pasta-rice/rice",
    "02-fmcg/categories/food/pantry/pasta-rice/noodles",
    "02-fmcg/categories/food/pantry/pasta-rice/grains",
    "02-fmcg/categories/food/pantry/pasta-rice/lentils",
    "02-fmcg/categories/food/pantry/pasta-rice/couscous",
    "02-fmcg/categories/food/pantry/pasta-rice/quinoa",
    # food/pantry/cooking-oils
    "02-fmcg/categories/food/pantry/cooking-oils/sunflower",
    "02-fmcg/categories/food/pantry/cooking-oils/olive",
    "02-fmcg/categories/food/pantry/cooking-oils/vegetable",
    "02-fmcg/categories/food/pantry/cooking-oils/coconut",
    "02-fmcg/categories/food/pantry/cooking-oils/palm",
    "02-fmcg/categories/food/pantry/cooking-oils/ghee",
    # food/pantry/sauces-marinades
    "02-fmcg/categories/food/pantry/sauces-marinades/pasta-sauce",
    "02-fmcg/categories/food/pantry/sauces-marinades/curry-sauce",
    "02-fmcg/categories/food/pantry/sauces-marinades/stir-fry",
    "02-fmcg/categories/food/pantry/sauces-marinades/bbq-sauce",
    "02-fmcg/categories/food/pantry/sauces-marinades/teriyaki",
    "02-fmcg/categories/food/pantry/sauces-marinades/pesto",
    "02-fmcg/categories/food/pantry/sauces-marinades/gravy",
    # food/pantry/herbs-spices
    "02-fmcg/categories/food/pantry/herbs-spices/whole-spices",
    "02-fmcg/categories/food/pantry/herbs-spices/ground-spices",
    "02-fmcg/categories/food/pantry/herbs-spices/spice-blends",
    "02-fmcg/categories/food/pantry/herbs-spices/herbs",
    "02-fmcg/categories/food/pantry/herbs-spices/seasoning-mixes",
    "02-fmcg/categories/food/pantry/herbs-spices/salt-pepper",
    "02-fmcg/categories/food/pantry/herbs-spices/rubs",
    # food/pantry/spreads
    "02-fmcg/categories/food/pantry/spreads/jam",
    "02-fmcg/categories/food/pantry/spreads/honey",
    "02-fmcg/categories/food/pantry/spreads/peanut-butter",
    "02-fmcg/categories/food/pantry/spreads/nutella",
    "02-fmcg/categories/food/pantry/spreads/marmalade",
    "02-fmcg/categories/food/pantry/spreads/tahini",
    # food/pantry/soup
    "02-fmcg/categories/food/pantry/soup/canned-soup",
    "02-fmcg/categories/food/pantry/soup/instant-soup",
    "02-fmcg/categories/food/pantry/soup/broth-stock",
    "02-fmcg/categories/food/pantry/soup/cup-noodles",
    # food/deli
    "02-fmcg/categories/food/deli/deli-meats",
    "02-fmcg/categories/food/deli/cheese-slices",
    "02-fmcg/categories/food/deli/prepared-salads",
    "02-fmcg/categories/food/deli/hummus",
    "02-fmcg/categories/food/deli/olives",
    "02-fmcg/categories/food/deli/charcuterie",
    "02-fmcg/categories/food/deli/ready-to-eat",
    # food/frozen
    "02-fmcg/categories/food/frozen/frozen-meals/ready-meals",
    "02-fmcg/categories/food/frozen/frozen-meals/frozen-pizza",
    "02-fmcg/categories/food/frozen/frozen-meals/frozen-pasta",
    "02-fmcg/categories/food/frozen/frozen-meals/frozen-curry",
    "02-fmcg/categories/food/frozen/frozen-meals/frozen-rice",
    "02-fmcg/categories/food/frozen/frozen-meals/burritos",
    "02-fmcg/categories/food/frozen/frozen-breakfast/waffles",
    "02-fmcg/categories/food/frozen/frozen-breakfast/pancakes",
    "02-fmcg/categories/food/frozen/frozen-breakfast/hash-browns",
    "02-fmcg/categories/food/frozen/frozen-meat-seafood/frozen-chicken",
    "02-fmcg/categories/food/frozen/frozen-meat-seafood/frozen-beef",
    "02-fmcg/categories/food/frozen/frozen-meat-seafood/frozen-fish",
    "02-fmcg/categories/food/frozen/frozen-meat-seafood/frozen-shrimp",
    "02-fmcg/categories/food/frozen/frozen-meat-seafood/frozen-burgers",
    "02-fmcg/categories/food/frozen/frozen-produce/frozen-vegetables",
    "02-fmcg/categories/food/frozen/frozen-produce/frozen-fruits",
    "02-fmcg/categories/food/frozen/frozen-produce/frozen-herbs",
    "02-fmcg/categories/food/frozen/frozen-desserts/ice-cream",
    "02-fmcg/categories/food/frozen/frozen-desserts/sorbet",
    "02-fmcg/categories/food/frozen/frozen-desserts/frozen-yogurt",
    "02-fmcg/categories/food/frozen/frozen-desserts/ice-lollies",
    "02-fmcg/categories/food/frozen/frozen-snacks/spring-rolls",
    "02-fmcg/categories/food/frozen/frozen-snacks/samosas",
    "02-fmcg/categories/food/frozen/frozen-snacks/nuggets",
    "02-fmcg/categories/food/frozen/frozen-snacks/fries",
    "02-fmcg/categories/food/frozen/frozen-snacks/onion-rings",
    # food/snacks
    "02-fmcg/categories/food/snacks/chips-crisps",
    "02-fmcg/categories/food/snacks/popcorn",
    "02-fmcg/categories/food/snacks/pretzels",
    "02-fmcg/categories/food/snacks/rice-cakes",
    "02-fmcg/categories/food/snacks/nuts-trail-mix",
    "02-fmcg/categories/food/snacks/fruit-snacks",
    "02-fmcg/categories/food/snacks/jerky",
    "02-fmcg/categories/food/snacks/crackers",
    "02-fmcg/categories/food/snacks/granola-bars",
    # food/candy-chocolate
    "02-fmcg/categories/food/candy-chocolate/chocolate-bars",
    "02-fmcg/categories/food/candy-chocolate/boxed-chocolates",
    "02-fmcg/categories/food/candy-chocolate/gummies",
    "02-fmcg/categories/food/candy-chocolate/hard-candy",
    "02-fmcg/categories/food/candy-chocolate/lollipops",
    "02-fmcg/categories/food/candy-chocolate/mints",
    "02-fmcg/categories/food/candy-chocolate/gum",
    "02-fmcg/categories/food/candy-chocolate/toffees",
    "02-fmcg/categories/food/candy-chocolate/marshmallows",
    # food/beverages
    "02-fmcg/categories/food/beverages/carbonated/cola",
    "02-fmcg/categories/food/beverages/carbonated/lemon-lime",
    "02-fmcg/categories/food/beverages/carbonated/energy-drinks",
    "02-fmcg/categories/food/beverages/carbonated/sparkling-water",
    "02-fmcg/categories/food/beverages/carbonated/flavored-soda",
    "02-fmcg/categories/food/beverages/non-carbonated/fruit-juice",
    "02-fmcg/categories/food/beverages/non-carbonated/nectar",
    "02-fmcg/categories/food/beverages/non-carbonated/smoothies",
    "02-fmcg/categories/food/beverages/non-carbonated/coconut-water",
    "02-fmcg/categories/food/beverages/non-carbonated/sports-drinks",
    "02-fmcg/categories/food/beverages/hot-drinks/coffee",
    "02-fmcg/categories/food/beverages/hot-drinks/tea",
    "02-fmcg/categories/food/beverages/hot-drinks/hot-chocolate",
    "02-fmcg/categories/food/beverages/hot-drinks/herbal-tea",
    "02-fmcg/categories/food/beverages/hot-drinks/instant-coffee",
    "02-fmcg/categories/food/beverages/hot-drinks/matcha",
    "02-fmcg/categories/food/beverages/alcohol/beer",
    "02-fmcg/categories/food/beverages/alcohol/wine",
    "02-fmcg/categories/food/beverages/alcohol/spirits",
    "02-fmcg/categories/food/beverages/alcohol/cocktails",
    "02-fmcg/categories/food/beverages/alcohol/non-alcoholic-beer",
    "02-fmcg/categories/food/beverages/kids-drinks/juice-boxes",
    "02-fmcg/categories/food/beverages/kids-drinks/flavored-milk",
    "02-fmcg/categories/food/beverages/kids-drinks/smoothie-pouches",
    # food/baking
    "02-fmcg/categories/food/baking/flour",
    "02-fmcg/categories/food/baking/sugar",
    "02-fmcg/categories/food/baking/baking-powder",
    "02-fmcg/categories/food/baking/yeast",
    "02-fmcg/categories/food/baking/vanilla",
    "02-fmcg/categories/food/baking/frosting",
    "02-fmcg/categories/food/baking/cake-mix",
    # food/baby-food
    "02-fmcg/categories/food/baby-food/infant-formula",
    "02-fmcg/categories/food/baby-food/purees",
    "02-fmcg/categories/food/baby-food/finger-foods",
    "02-fmcg/categories/food/baby-food/toddler-meals",
    "02-fmcg/categories/food/baby-food/baby-cereal",
    "02-fmcg/categories/food/baby-food/baby-snacks",
    # food/health-free-from
    "02-fmcg/categories/food/health-free-from/gluten-free",
    "02-fmcg/categories/food/health-free-from/vegan",
    "02-fmcg/categories/food/health-free-from/organic",
    "02-fmcg/categories/food/health-free-from/keto",
    "02-fmcg/categories/food/health-free-from/dairy-free",
    "02-fmcg/categories/food/health-free-from/high-protein",
    "02-fmcg/categories/food/health-free-from/plant-based",
    # food/international
    "02-fmcg/categories/food/international/asian-foods",
    "02-fmcg/categories/food/international/indian-foods",
    "02-fmcg/categories/food/international/mexican-foods",
    "02-fmcg/categories/food/international/mediterranean",
    "02-fmcg/categories/food/international/middle-eastern",
    "02-fmcg/categories/food/international/african",
    "02-fmcg/categories/food/international/latin-american",
    # personal-care
    "02-fmcg/categories/personal-care/skincare/face-wash",
    "02-fmcg/categories/personal-care/skincare/moisturizers",
    "02-fmcg/categories/personal-care/skincare/sunscreen",
    "02-fmcg/categories/personal-care/skincare/serums",
    "02-fmcg/categories/personal-care/skincare/masks",
    "02-fmcg/categories/personal-care/skincare/toners",
    "02-fmcg/categories/personal-care/skincare/eye-cream",
    "02-fmcg/categories/personal-care/skincare/body-lotion",
    "02-fmcg/categories/personal-care/haircare/shampoo",
    "02-fmcg/categories/personal-care/haircare/conditioner",
    "02-fmcg/categories/personal-care/haircare/hair-oil",
    "02-fmcg/categories/personal-care/haircare/hair-color",
    "02-fmcg/categories/personal-care/haircare/treatments",
    "02-fmcg/categories/personal-care/haircare/styling",
    "02-fmcg/categories/personal-care/haircare/dry-shampoo",
    "02-fmcg/categories/personal-care/hygiene/soaps",
    "02-fmcg/categories/personal-care/hygiene/body-wash",
    "02-fmcg/categories/personal-care/hygiene/sanitizers",
    "02-fmcg/categories/personal-care/hygiene/deodorants",
    "02-fmcg/categories/personal-care/hygiene/feminine-care",
    "02-fmcg/categories/personal-care/hygiene/wet-wipes",
    "02-fmcg/categories/personal-care/oral-care/toothpaste",
    "02-fmcg/categories/personal-care/oral-care/toothbrush",
    "02-fmcg/categories/personal-care/oral-care/mouthwash",
    "02-fmcg/categories/personal-care/oral-care/floss",
    "02-fmcg/categories/personal-care/oral-care/whitening",
    "02-fmcg/categories/personal-care/mens-grooming/shaving",
    "02-fmcg/categories/personal-care/mens-grooming/aftershave",
    "02-fmcg/categories/personal-care/mens-grooming/beard-care",
    "02-fmcg/categories/personal-care/mens-grooming/mens-skincare",
    "02-fmcg/categories/personal-care/mens-grooming/deodorant",
    "02-fmcg/categories/personal-care/cosmetics/lipstick",
    "02-fmcg/categories/personal-care/cosmetics/foundation",
    "02-fmcg/categories/personal-care/cosmetics/mascara",
    "02-fmcg/categories/personal-care/cosmetics/eyeshadow",
    "02-fmcg/categories/personal-care/cosmetics/blush",
    "02-fmcg/categories/personal-care/cosmetics/nail-polish",
    "02-fmcg/categories/personal-care/cosmetics/fragrance",
    # home-care
    "02-fmcg/categories/home-care/detergents/laundry-powder",
    "02-fmcg/categories/home-care/detergents/liquid-detergent",
    "02-fmcg/categories/home-care/detergents/fabric-softener",
    "02-fmcg/categories/home-care/detergents/stain-remover",
    "02-fmcg/categories/home-care/detergents/washing-pods",
    "02-fmcg/categories/home-care/cleaners/floor-cleaner",
    "02-fmcg/categories/home-care/cleaners/glass-cleaner",
    "02-fmcg/categories/home-care/cleaners/kitchen-cleaner",
    "02-fmcg/categories/home-care/cleaners/bathroom-cleaner",
    "02-fmcg/categories/home-care/cleaners/disinfectant",
    "02-fmcg/categories/home-care/cleaners/bleach",
    "02-fmcg/categories/home-care/cleaners/toilet-cleaner",
    "02-fmcg/categories/home-care/paper/toilet-paper",
    "02-fmcg/categories/home-care/paper/kitchen-towel",
    "02-fmcg/categories/home-care/paper/tissues",
    "02-fmcg/categories/home-care/paper/napkins",
    "02-fmcg/categories/home-care/paper/wipes",
    "02-fmcg/categories/home-care/paper/bin-liners",
    "02-fmcg/categories/home-care/tools/brooms",
    "02-fmcg/categories/home-care/tools/mops",
    "02-fmcg/categories/home-care/tools/sponges",
    "02-fmcg/categories/home-care/tools/gloves",
    "02-fmcg/categories/home-care/tools/brushes",
    "02-fmcg/categories/home-care/air-care/air-fresheners",
    "02-fmcg/categories/home-care/air-care/candles",
    "02-fmcg/categories/home-care/air-care/diffusers",
    "02-fmcg/categories/home-care/air-care/insecticide",
    "02-fmcg/categories/home-care/pest-control/insect-killers",
    "02-fmcg/categories/home-care/pest-control/rodent-control",
    "02-fmcg/categories/home-care/pest-control/mosquito-repellent",
    # baby-care
    "02-fmcg/categories/baby-care/diapers/newborn-diapers",
    "02-fmcg/categories/baby-care/diapers/infant-diapers",
    "02-fmcg/categories/baby-care/diapers/toddler-diapers",
    "02-fmcg/categories/baby-care/diapers/swim-diapers",
    "02-fmcg/categories/baby-care/diapers/training-pants",
    "02-fmcg/categories/baby-care/feeding/bottles",
    "02-fmcg/categories/baby-care/feeding/formula",
    "02-fmcg/categories/baby-care/feeding/sippy-cups",
    "02-fmcg/categories/baby-care/feeding/bibs",
    "02-fmcg/categories/baby-care/baby-skincare/baby-lotion",
    "02-fmcg/categories/baby-care/baby-skincare/baby-shampoo",
    "02-fmcg/categories/baby-care/baby-skincare/baby-wipes",
    "02-fmcg/categories/baby-care/baby-skincare/nappy-cream",
    # pet-care
    "02-fmcg/categories/pet-care/dog/dog-food-dry",
    "02-fmcg/categories/pet-care/dog/dog-food-wet",
    "02-fmcg/categories/pet-care/dog/dog-treats",
    "02-fmcg/categories/pet-care/dog/dog-grooming",
    "02-fmcg/categories/pet-care/dog/dog-toys",
    "02-fmcg/categories/pet-care/cat/cat-food-dry",
    "02-fmcg/categories/pet-care/cat/cat-food-wet",
    "02-fmcg/categories/pet-care/cat/cat-treats",
    "02-fmcg/categories/pet-care/cat/cat-litter",
    "02-fmcg/categories/pet-care/cat/cat-toys",
    "02-fmcg/categories/pet-care/other/fish-food",
    "02-fmcg/categories/pet-care/other/bird-food",
    "02-fmcg/categories/pet-care/other/small-animal-food",
    # health-wellness
    "02-fmcg/categories/health-wellness/vitamins",
    "02-fmcg/categories/health-wellness/supplements",
    "02-fmcg/categories/health-wellness/protein",
    "02-fmcg/categories/health-wellness/OTC-medicines",
    "02-fmcg/categories/health-wellness/first-aid",
    "02-fmcg/categories/health-wellness/digestive-health",
    "02-fmcg/categories/health-wellness/cold-flu",
]


def main():
    parser = argparse.ArgumentParser(
        description="Create missing folders under public/assets/verticals/ (safe, idempotent)."
    )
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be created, but create nothing.")
    parser.add_argument("--vertical", choices=["01-apparels", "02-fmcg"],
                        help="Limit to one vertical.")
    args = parser.parse_args()

    if not os.path.isdir(BASE):
        print(f"ERROR: base path does not exist: {BASE}", file=sys.stderr)
        sys.exit(1)

    paths = PATHS
    if args.vertical:
        paths = [p for p in paths if p.startswith(args.vertical + "/")]

    created = 0
    skipped = 0
    mode = "DRY-RUN" if args.dry_run else "APPLY"
    print(f"=== {mode} ===  base: {BASE}  paths: {len(paths)}\n")

    for rel in paths:
        full = os.path.join(BASE, rel)
        if os.path.isdir(full):
            skipped += 1
            continue
        if args.dry_run:
            print(f"WOULD CREATE: public/assets/verticals/{rel}")
            created += 1
        else:
            os.makedirs(full, exist_ok=True)
            print(f"CREATED:      public/assets/verticals/{rel}")
            created += 1

    print()
    print(f"=== SUMMARY ===")
    print(f"Created: {created} | Skipped: {skipped} | Total: {len(paths)}")
    if args.dry_run:
        print("(dry-run — no changes were made)")


if __name__ == "__main__":
    main()
